/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SYSTESTGROUP_H
#define SYSTESTGROUP_H

/* function declarations */
void init_sysTestGroup(void);
Netsnmp_Node_Handler handle_sysTestOSName;
Netsnmp_Node_Handler handle_sysTestUpTimeTicks;
Netsnmp_Node_Handler handle_sysTestCurrentProcsNum;
Netsnmp_Node_Handler handle_sysTestTestVar1;

#endif /* SYSTESTGROUP_H */
