/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <sys/sysinfo.h>
#include <sys/utsname.h>
#include "sysTestGroup.h"

/** Initializes the sysTestGroup module */
void
init_sysTestGroup(void)
{
    const oid sysTestOSName_oid[] = { 1,3,6,1,4,1,37267,1,1 };
    const oid sysTestUpTimeTicks_oid[] = { 1,3,6,1,4,1,37267,1,2 };
    const oid sysTestCurrentProcsNum_oid[] = { 1,3,6,1,4,1,37267,1,3 };
    const oid sysTestTestVar1_oid[] = { 1,3,6,1,4,1,37267,1,4 };

        DEBUGMSGTL(("sysTestGroup", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysTestOSName", handle_sysTestOSName,
                               sysTestOSName_oid, OID_LENGTH(sysTestOSName_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysTestUpTimeTicks", handle_sysTestUpTimeTicks,
                               sysTestUpTimeTicks_oid, OID_LENGTH(sysTestUpTimeTicks_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysTestCurrentProcsNum", handle_sysTestCurrentProcsNum,
                               sysTestCurrentProcsNum_oid, OID_LENGTH(sysTestCurrentProcsNum_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysTestTestVar1", handle_sysTestTestVar1,
                               sysTestTestVar1_oid, OID_LENGTH(sysTestTestVar1_oid),
                               HANDLER_CAN_RWRITE
        ));
}

int
handle_sysTestOSName(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {
        case MODE_GET:
            struct utsname info;
            uname(&info);
            const char *result = info.sysname;
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                    (u_char *) result,
                                    strlen(result));
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysTestOSName\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_sysTestUpTimeTicks(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {
        case MODE_GET:
            struct sysinfo info;
            sysinfo(&info);
            const long result = info.uptime * 100;
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                     (u_char *)&result,
                                     sizeof(info.uptime));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysTestUpTimeTicks\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_sysTestCurrentProcsNum(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {
        case MODE_GET:
            struct sysinfo info;
            sysinfo(&info);// devuelve informacion sobre estadisticas globales del sistema
            const int num = info.procs;//numero de procesos
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &num,// here was num variable
                                     sizeof(num));
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysTestCurrentProcsNum\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_sysTestTestVar1(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    static int variable1 = 0;// some initial value
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {
        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     (u_char *) &variable1,// here was num variable
                                     sizeof(variable1));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
            /* or you could use netsnmp_check_vb_type_and_size instead */
            int ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error (reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            if (FALSE /* XXX if malloc, or whatever, failed: */) {
                netsnmp_set_request_error (reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            variable1 = *requests->requestvb->val.integer;
            if (FALSE /* XXX: error? */) {
                netsnmp_set_request_error (reqinfo, requests, SNMP_ERR_GENERR);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            if (FALSE /* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error (reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            if (FALSE /* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error (reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysTestTestVar1\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
